### ISSUE TITLE
[Adaptive Navigation] Menu icon is not center aligned with navigation rail items

### ISSUE THREAD

**Issue by clocksmith** [material-components/material-components-flutter-adaptive#2]
Currently:
![Screen Shot 2020-08-11 at 1 36 29 PM](https://user-images.githubusercontent.com/591699/89929902-e682ba00-dbd7-11ea-8265-94849522af0c.png)

Should be more like:
![Screen Shot 2020-08-11 at 1 37 17 PM](https://user-images.githubusercontent.com/591699/89929938-ee425e80-dbd7-11ea-9d25-8e5623ce0cc5.png)

**Comment by clocksmith** [comment]
One solution here would be to create an AdaptiveAppBar (that wraps a regular AppBar) that can adjust the menu icon position

**Comment by clocksmith** [comment]
This is not fixed because the existing solution only takes the medium screen size into account, but the rail can be configured to show up on other screen sizes

**Comment by clocksmith** [comment]
A possible solution to investigate is to make a parameter on the AppBar that is themable in the framework, and use that theme here. This would require a change to the framework.

**Comment by fredgrott** [comment]
ahem this might work:

line about 72 right after build

double grottify() {
      double me;

      me = getWindowType(context) == AdaptiveWindowType.large ? 96.0 : 72.0;
      me = getWindowType(context) == AdaptiveWindowType.medium ? 72.0 : 56.0;

      return me;
    }

then at  leadingWidth:

grottify()

its ugly but quick and probably works :)

well at leas until any framework changes :)
