### ISSUE TITLE
UX implications question

### ISSUE THREAD

**Issue by fredgrott** [material-components/material-components-flutter-adaptive#45]
Has anyone at Google thought about studying the UX implications of switching form List View Feeds to Gird View list feeds for non visual lists as a way to decrease the polarization and poisonous behavior of threat actors on social platforms?

For example, with Google one of their own social platforms left is GMail, what would happen if we switch it from list view list feeds to to gridview list feeds?

Yeah, it is stretching the adaptive defintion.

**Comment by guidezpl** [comment]
I'm not sure I understand the question, but we do have some "research" & recommendation here https://material.io/archive/guidelines/components/grid-lists.html#
